development:
  adapter: mysql2
  encoding: utf8
  database: simple_cms_development
  pool: 5
  username: simple_cms
  password: secretpassword
  socket: /tmp/mysql.sock

# test:
#   adapter: mysql
#   encoding: utf8
#   reconnect: false
#   database: **myapp_test**
#   pool: 5
#   username: **root**
#   password: **supersecretpassword**
#   socket: **/opt/local/var/run/mysql5/mysqld.sock**

# production:
#   adapter: mysql
#   encoding: utf8
#   reconnect: false
#   database: **myapp_production**
#   pool: 5
#   username: **root**
#   password: **supersecretpassword**
#   socket: **/opt/local/var/run/mysql5/mysqld.sock**